# TCL File Generated by Component Editor 9.0
# Tue Nov 11 15:35:02 PST 2008
# DO NOT MODIFY


# +-----------------------------------
# | module altera_jtag_avalon_master
# | 
set_module_property NAME altera_jtag_avalon_master
set_module_property DESCRIPTION "The JTAG to Avalon Master Bridge is a collection of pre-wired components that provide an Avalon Master using the new JTAG channel."
set_module_property VERSION "9.0"
set_module_property GROUP "Bridges and Adapters/Memory Mapped"
set_module_property AUTHOR  "Altera Corporation"
set_module_property DISPLAY_NAME "JTAG to Avalon Master Bridge" 
set_module_property DATASHEET_URL "http://www.altera.com/literature/hb/nios2/qts_qii55011.pdf"
set_module_property TOP_LEVEL_HDL_FILE altera_jtag_avalon_master.v
set_module_property TOP_LEVEL_HDL_MODULE altera_jtag_avalon_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file altera_jtag_avalon_master.v {SYNTHESIS SIMULATION}
add_file altera_jtag_avalon_master_pli_off.v {SYNTHESIS SIMULATION}
add_file altera_jtag_avalon_master_pli_on.v {SYNTHESIS SIMULATION}
add_file altera_jtag_avalon_master_common_modules.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_st_packets_to_bytes/altera_avalon_st_packets_to_bytes.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_jtag_phy/altera_avalon_st_jtag_interface.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_jtag_phy/altera_jtag_dc_streaming.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_jtag_phy/altera_jtag_phy.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_jtag_phy/altera_jtag_streaming.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_jtag_phy/altera_pli_streaming.v {SYNTHESIS SIMULATION}
add_file ../../primitives/altera_avalon_st_clock_crosser/altera_avalon_st_clock_crosser.v {SYNTHESIS SIMULATION}
add_file ../../primitives/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_stage.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_st_idle_remover/altera_avalon_st_idle_remover.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_st_idle_inserter/altera_avalon_st_idle_inserter.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_sc_fifo/altera_avalon_sc_fifo.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_packets_to_master/altera_avalon_packets_to_master.v {SYNTHESIS SIMULATION}
add_file ../altera_avalon_st_bytes_to_packets/altera_avalon_st_bytes_to_packets.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | simulation libraries 
# | 
add_file ../altera_avalon_jtag_phy/bytestream_pli.dll SIMULATION
set_file_property bytestream_pli.dll PLUGIN_API "win32 pli"
add_file ../altera_avalon_jtag_phy/libbytestream_pli.so SIMULATION
set_file_property libbytestream_pli.so PLUGIN_API "linux pli"
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter USE_PLI INTEGER 0
set_parameter_property USE_PLI DISPLAY_NAME "Use PLI Simulation Mode" 
set_parameter_property USE_PLI UNITS None
set_parameter_property USE_PLI DISPLAY_HINT ""
set_parameter_property USE_PLI AFFECTS_GENERATION false
set_parameter_property USE_PLI IS_HDL_PARAMETER true
set_parameter_property USE_PLI STATUS experimental

add_parameter PLI_PORT INTEGER 50000
set_parameter_property PLI_PORT DISPLAY_NAME PLI_PORT
set_parameter_property PLI_PORT UNITS None
set_parameter_property PLI_PORT DISPLAY_HINT ""
set_parameter_property PLI_PORT AFFECTS_GENERATION false
set_parameter_property PLI_PORT IS_HDL_PARAMETER true
set_parameter_property PLI_PORT STATUS experimental
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ptfSchematicName ""

set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1
add_interface_port clk reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point master
# | 
add_interface master avalon start
set_interface_property master adaptsTo ""
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master linewrapBursts false

set_interface_property master ASSOCIATED_CLOCK clk
set_interface_property master ENABLED true

add_interface_port master resetrequest_from_the_altera_jtag_avalon_master_jtag_interface resetrequest Output 1
add_interface_port master address_from_the_altera_jtag_avalon_master_packets_to_transactions_converter address Output 32
add_interface_port master byteenable_from_the_altera_jtag_avalon_master_packets_to_transactions_converter byteenable Output 4
add_interface_port master read_from_the_altera_jtag_avalon_master_packets_to_transactions_converter read Output 1
add_interface_port master readdata_to_the_altera_jtag_avalon_master_packets_to_transactions_converter readdata Input 32
add_interface_port master readdatavalid_to_the_altera_jtag_avalon_master_packets_to_transactions_converter readdatavalid Input 1
add_interface_port master waitrequest_to_the_altera_jtag_avalon_master_packets_to_transactions_converter waitrequest Input 1
add_interface_port master write_from_the_altera_jtag_avalon_master_packets_to_transactions_converter write Output 1
add_interface_port master writedata_from_the_altera_jtag_avalon_master_packets_to_transactions_converter writedata Output 32
# | 
# +-----------------------------------
