# TCL file for SPISlaveToAvalonMasterBridge
# NOT generated by Component Editor 
# DO NOT MODIFYy

set_source_file SPISlaveToAvalonMasterBridge.v
set_module SPISlaveToAvalonMasterBridge
set_module_description "SPI Slave To Avalon Master Bridge is a collection of pre-wired components that provide an Avalon Master using an external SPI interface "
set_module_property author  "Altera Corporation"
set_module_property className  "spi_slave_to_avalon_mm_master_bridge"
set_module_property displayName  "SPI Slave to Avalon Master Bridge"
set_module_property group  "Bridges and Adapters/Memory Mapped"
set_module_property instantiateInSystemModule  "true"
set_module_property version "9.0"
set_module_property datasheetURL "http://www.altera.com/literature/hb/nios2/qts_qii55011.pdf"
set_module_property editable "false"
set hdl_files [list SPISlaveToAvalonMasterBridge.v \
altera_avalon_packets_to_master_inst_for_spichain.v \
altera_avalon_st_bytes_to_packets_inst_for_spichain.v \
altera_avalon_st_packets_to_bytes_inst_for_spichain.v \
channel_adapter_btop_for_spichain.v \
channel_adapter_ptob_for_spichain.v \
spislave_inst_for_spichain.v \
../altera_avalon_packets_to_master/altera_avalon_packets_to_master.v \
../altera_avalon_st_bytes_to_packets/altera_avalon_st_bytes_to_packets.v \
../altera_avalon_st_packets_to_bytes/altera_avalon_st_packets_to_bytes.v \
../altera_avalon_spi_phy_slave/spiphyslave.v]
add_file "../altera_avalon_spi_phy_slave/spiphyslave.sdc" SDC

set_module_property simulationFiles $hdl_files
set_module_property synthesisFiles $hdl_files

# Module parameters
add_parameter "SYNC_DEPTH" "integer" "2" "Set the depth of the synchronization registers"
set_parameter_property "SYNC_DEPTH" "DISPLAY_NAME" "Depth"
set_parameter_property "SYNC_DEPTH" "ALLOWED_RANGES" {2 3 4 5}
set_parameter_property "SYNC_DEPTH" "AFFECTS_PORT_WIDTHS" "false"
set_parameter_property "SYNC_DEPTH" "GROUP" "Number of synchronizer stages"
set_parameter_property "SYNC_DEPTH" "VISIBLE" "true"

# Interface clk
add_interface clk clock sink asynchronous
# Ports in interface clk
add_port_to_interface clk clk clk
add_port_to_interface clk reset_n reset_n

# Interface export_0
add_interface "export_0" "conduit" "start" "asynchronous"
# Ports in interface export_0
add_port_to_interface "export_0" "mosi_to_the_spislave_inst_for_spichain" "export"
add_port_to_interface "export_0" "nss_to_the_spislave_inst_for_spichain" "export"
add_port_to_interface "export_0" "miso_to_and_from_the_spislave_inst_for_spichain" "export"
add_port_to_interface "export_0" "sclk_to_the_spislave_inst_for_spichain" "export"

# Interface avalon_master
add_interface avalon_master avalon master clk
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master burstOnBurstBoundariesOnly false

# Ports in interface avalon_master
add_port_to_interface avalon_master address_from_the_altera_avalon_packets_to_master_inst_for_spichain address
add_port_to_interface avalon_master byteenable_from_the_altera_avalon_packets_to_master_inst_for_spichain byteenable
add_port_to_interface avalon_master read_from_the_altera_avalon_packets_to_master_inst_for_spichain read
add_port_to_interface avalon_master readdata_to_the_altera_avalon_packets_to_master_inst_for_spichain readdata
add_port_to_interface avalon_master readdatavalid_to_the_altera_avalon_packets_to_master_inst_for_spichain readdatavalid
add_port_to_interface avalon_master waitrequest_to_the_altera_avalon_packets_to_master_inst_for_spichain waitrequest
add_port_to_interface avalon_master write_from_the_altera_avalon_packets_to_master_inst_for_spichain write
add_port_to_interface avalon_master writedata_from_the_altera_avalon_packets_to_master_inst_for_spichain writedata




