# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -lazy" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ::quartus::xmltiming 1.0 [list tclPkgSetup $dir ::quartus::xmltiming 1.0 {{xmltiming.tcl source {::quartus::xmltiming::build_cache ::quartus::xmltiming::clear_cached_data ::quartus::xmltiming::get_attributes ::quartus::xmltiming::get_block_types ::quartus::xmltiming::get_delay ::quartus::xmltiming::get_general_microparameter ::quartus::xmltiming::get_general_microparameters ::quartus::xmltiming::get_inputs ::quartus::xmltiming::get_locations ::quartus::xmltiming::get_outputs ::quartus::xmltiming::get_register_microparameter ::quartus::xmltiming::get_register_microparameters}}}]
package ifneeded ::quartus::xmltiming::db 1.0 [list source [file join $dir db.tcl]]
