# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -lazy" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ::qboard::cc 1.0 [list tclPkgSetup $dir ::qboard::cc 1.0 {{qboard-cc-pkg.tcl source {::qboard::cc::get_name ::qboard::cc::get_revision ::qboard::cc::set_default_assignments}}}]
package ifneeded ::qboard::de1 1.0 [list tclPkgSetup $dir ::qboard::de1 1.0 {{qboard-de1-pkg.tcl source {::qboard::de1::get_name ::qboard::de1::get_revision ::qboard::de1::set_default_assignments}}}]
package ifneeded ::qboard::de2 1.0 [list tclPkgSetup $dir ::qboard::de2 1.0 {{qboard-de2-pkg.tcl source {::qboard::de2::get_name ::qboard::de2::get_revision ::qboard::de2::set_default_assignments}}}]
package ifneeded ::qboard::den 1.0 [list tclPkgSetup $dir ::qboard::den 1.0 {{qboard-den-pkg.tcl source {::qboard::den::get_name ::qboard::den::get_revision ::qboard::den::set_default_assignments}}}]
