set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|is_sample_count_f0[*]}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|is_line_count_f0[*]}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|is_sample_count_f1[*]}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|is_line_count_f1[*]}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|is_stable}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|is_interlaced}]

set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:clear_overflow_sticky_sync|data_out_sync0}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:enable_resync_sync|data_out_sync0}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:enable_sync|data_out_sync0}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:overflow_sticky_sync|data_out_sync0}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:update_sync|data_out_sync0}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:vid_locked_sync|data_out_sync0}]
set_false_path -to [get_keepers {*alt_vip_Vid2IS:*|alt_vip_common_sync:field_prediction_sync|data_out_sync0}]
