# TCL File Generated by Component Editor on: 
# Mon May 14 15:31:17 PDT 2007
# DO NOT MODIFY

set_module_property "TOP_LEVEL_HDL_FILE" "altera_avalon_remote_update_cycloneiii.v"
set_module_property "TOP_LEVEL_HDL_MODULE" "altera_avalon_remote_update_cycloneiii"
set_module_property "DESCRIPTION" ""
set_module_property "className" "altera_avalon_remote_update_cycloneiii"
set_module_property instantiateInSystemModule true
set_module_property author  "Altera Corporation"
set_module_property version "9.0"
set_module_property group "Peripherals/FPGA Peripherals"
set_module_property editable false
add_file "altera_avalon_remote_update_cycloneiii.v" {SYNTHESIS SIMULATION}
set_module_property displayName "Remote Update Controller (Cyclone III)"
set_module_property datasheetURL "http://www.altera.com/literature/hb/nios2/qts_qii55017.pdf"
set_module_property simulationModelInVHDL "true"
set_module_property simulationModelInVerilog "true"

# Module parameters

set_module_property previewElaborationCallback "elaborate"
proc elaborate {} {

	# Clock Interface global_signals_clock
	add_interface          "global_signals_clock" "clock" "end"
	# Ports in interface global_signals_clock
	add_interface_port "global_signals_clock" "clk" "clk" "input" 1
	add_interface_port "global_signals_clock" "reset" "reset" "input" 1
	
	# Interface s1
	add_interface "s1" "avalon" "slave" "global_signals_clock"
	set_interface_property "s1" "isNonVolatileStorage" "false"
	set_interface_property "s1" "burstOnBurstBoundariesOnly" "false"
	set_interface_property "s1" "transparentBridge" "false"
	set_interface_property "s1" "readLatency" "2"
	set_interface_property "s1" "readWaitStates" "0"
	set_interface_property "s1" "isFlash" "false"
	set_interface_property "s1" "holdTime" "0"
	set_interface_property "s1" "printableDevice" "false"
	set_interface_property "s1" "registerIncomingSignals" "false"
	set_interface_property "s1" "readWaitTime" "0"
	set_interface_property "s1" "setupTime" "0"
	set_interface_property "s1" "addressGroup" "0"
	set_interface_property "s1" "interleaveBursts" "false"
	set_interface_property "s1" "addressAlignment" "NATIVE"
	set_interface_property "s1" "isBigEndian" "false"
	set_interface_property "s1" "writeLatency" "0"
	set_interface_property "s1" "writeWaitTime" "0"
	set_interface_property "s1" "timingUnits" "Cycles"
	set_interface_property "s1" "minimumUninterruptedRunLength" "1"
	set_interface_property "s1" "registerOutgoingSignals" "false"
	set_interface_property "s1" "addressSpan" "64"
	set_interface_property "s1" "isMemoryDevice" "false"
	set_interface_property "s1" "linewrapBursts" "false"
	set_interface_property "s1" "alwaysBurstMaxBurst" "false"
	set_interface_property "s1" "writeWaitStates" "0"
	set_interface_property "s1" "maximumPendingReadTransactions" "0"
	set_interface_property "s1" "wellBehavedWaitrequest" "false"
	# Ports in interface s1
	add_interface_port "s1" "writedata" "writedata" "input" 32
	add_interface_port "s1" "readdata" "readdata" "output" 32
	add_interface_port "s1" "address" "address" "input" 6
	add_interface_port "s1" "chipselect" "chipselect" "input" 1
	add_interface_port "s1" "write" "write" "input" 1
	add_interface_port "s1" "read" "read" "input" 1
	add_interface_port "s1" "waitrequest" "waitrequest" "output" 1
}
