##Legal Notice: (C)2006 Altera Corporation. All rights reserved. Your
##use of Altera Corporation's design tools, logic functions and other
##software and tools, and its AMPP partner logic functions, and any
##output files any of the foregoing (including device programming or
##simulation files), and any associated documentation or information are
##expressly subject to the terms and conditions of the Altera Program
##License Subscription Agreement or other applicable license agreement,
##including, without limitation, that your use is for the sole purpose
##of programming logic devices manufactured by Altera and sold by Altera
##or its authorized distributors. Please refer to the applicable
##agreement for further details. 


# This file is generated by the "pkg_mkIndex" command

# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related

# in response to "package require" commands.  When this


##nagelfar variable dir
package ifneeded ::ddr::data 0.1 [list source [file join $dir data.tcl]]
package ifneeded ::ddr::dotty 0.1 [list source [file join $dir dotty.tcl]]
package ifneeded ::ddr::dqsfbc 0.1 [list source [file join $dir dqsfbc.tcl]]
package ifneeded ::ddr::extract 0.1 [list source [file join $dir extract.tcl]]
package ifneeded ::ddr::file 0.1 [list source [file join $dir file.tcl]]
package ifneeded ::ddr::flowtools 0.1 [list source [file join $dir flowtools.tcl]]
package ifneeded ::ddr::legacy 0.1 [list source [file join $dir legacy.tcl]]
package ifneeded ::ddr::log 0.1 [list source [file join $dir log.tcl]]
package ifneeded ::ddr::messages 0.1 [list source [file join $dir messages.tcl]]
package ifneeded ::ddr::mwinterface 0.1 [list source [file join $dir mwinterface.tcl]]
package ifneeded ::ddr::nondqsfbc 0.1 [list source [file join $dir nondqsfbc.tcl]]
package ifneeded ::ddr::paths 0.1 [list source [file join $dir paths.tcl]]
package ifneeded ::ddr::pcinterface 0.1 [list source [file join $dir pcinterface.tcl]]
package ifneeded ::ddr::phasesel 0.1 [list source [file join $dir phasesel.tcl]]
package ifneeded ::ddr::s2dqs 0.1 [list source [file join $dir s2dqs.tcl]]
package ifneeded ::ddr::settings 0.1 [list source [file join $dir settings.tcl]]
package ifneeded ::ddr::type 0.1 [list source [file join $dir type.tcl]]
package ifneeded ::ddr::utils 0.1 [list source [file join $dir utils.tcl]]
